[workspace]
authors = ["Wingerted <wingerted@gmail.com>"]
channels = ["https://repo.prefix.dev/cxxlibs", "conda-forge"]
name = "reflect-cpp"
platforms = ["linux-64"]
version = "0.21.0"

[tasks]

[dependencies]
cmake = "*"
ninja = "*"
clang = "*"
clangxx = "*"
rattler-build = "*"
ccache = "*"
pkg-config = ">=0.29.2,<0.30"
ctre = ">=3.9.0,<4"
msgpack-c = ">=6.1.0,<7"
flatbuffers = ">=25.1.21,<26"
libbson = ">=1.23.2,<2"
pugixml = ">=1.15,<2"
yaml-cpp = ">=0.8.0,<0.9"
yyjson = ">=0.10.0,<0.11"
tomlplusplus = ">=3.4.0,<4"
pyarrow = ">=21.0.0,<22"

