context:
  version: 0.21.0

package:
  name: reflect-cpp
  version: ${{ version }}

source:
  git: https://github.com/getml/reflect-cpp.git
  tag: v${{ version }}
  patches:
    - fix_system_arrow_target.patch

build:
  script: ./build.sh

requirements:
  build:
    - clang
    - clangxx
    - cmake
    - ninja
  host:
    - ctre >=3.9.0,<4
    - msgpack-c >=6.1.0,<7
    - flatbuffers >=25.1.21,<26
    - libbson >=1.23.2,<2
    - pugixml >=1.15,<2
    - yaml-cpp >=0.8.0,<0.9
    - yyjson >=0.10.0,<0.11
    - tomlplusplus >=3.4.0,<4
    - pyarrow >=21.0.0,<22
  run:
    - ctre >=3.9.0,<4
    - msgpack-c >=6.1.0,<7
    - flatbuffers >=25.1.21,<26
    - libbson >=1.23.2,<2
    - pugixml >=1.15,<2
    - yaml-cpp >=0.8.0,<0.9
    - yyjson >=0.10.0,<0.11
    - tomlplusplus >=3.4.0,<4
    - pyarrow >=21.0.0,<22

# 包的元数据
about:
  homepage: https://github.com/getml/reflect-cpp
  license: MIT
  summary: A modern C++ reflection library
